### ISSUE TITLE
how to train it with cpu.

### ISSUE THREAD

**Issue by victorbai2** [LorrinWWW/two-are-better-than-one#5]
I got below error. I believe that it may be caused by gpu inavailability issue. Can you tell how to train with cpu?

```
site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/root/anaconda3/envs/env12_twoBetterOne/lib/python3.7/site-packages/pynvml.py", line 644, in _LoadNvmlLibrary
    nvmlLib = CDLL("libnvidia-ml.so.1")
  File "/root/anaconda3/envs/env12_twoBetterOne/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 197, in <module>
    gpu_idx, gpu_mem = set_max_available_gpu()
  File "/home/projects/information_extraction/two-are-better-than-one/utils/cuda.py", line 32, in set_max_available_gpu
    gpu_idx, gpu_mem = get_max_available_gpu()
  File "/home/projects/information_extraction/two-are-better-than-one/utils/cuda.py", line 26, in get_max_available_gpu
    gpu_available_memory_list = get_available_gpu_memory_list()
  File "/home/projects/information_extraction/two-are-better-than-one/utils/cuda.py", line 19, in get_available_gpu_memory_list
    ret = gpustat.new_query()
  File "/root/anaconda3/envs/env12_twoBetterOne/lib/python3.7/site-packages/gpustat/core.py", line 510, in new_query
    return GPUStatCollection.new_query()
  File "/root/anaconda3/envs/env12_twoBetterOne/lib/python3.7/site-packages/gpustat/core.py", line 281, in new_query
    N.nvmlInit()
  File "/root/anaconda3/envs/env12_twoBetterOne/lib/python3.7/site-packages/pynvml.py", line 608, in nvmlInit
    _LoadNvmlLibrary()
  File "/root/anaconda3/envs/env12_twoBetterOne/lib/python3.7/site-packages/pynvml.py", line 646, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/root/anaconda3/envs/env12_twoBetterOne/lib/python3.7/site-packages/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
```

**Comment by LorrinWWW** [comment]
Explicitly setting argument "--device cpu" should avoid this issue (not verified yet, may have a try?).
And, are you sure you want train with cpu? It may take several days to converge though.

**Comment by victorbai2** [comment]
@LorrinWWW  Hi thanks for your instant response. I got below error and it does not seem like that cpu works.
I am not familiar with torch and I think the below code may have caused the error:

> if args.device is not None:
>     torch.cuda.set_device(args.device)
> else:
>     gpu_idx, gpu_mem = set_max_available_gpu()
>     args.device = f"cuda:{gpu_idx}"

Any idea to change torch to use cpu only? coz I does not have any piece of GPU on my machine.

```
torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "train.py", line 195, in <module>
    torch.cuda.set_device(args.device)
  File "/root/anaconda3/envs/env12_twoBetterOne/lib/python3.7/site-packages/torch/cuda/__init__.py", line 261, in set_device
    device = _get_device_index(device)
  File "/root/anaconda3/envs/env12_twoBetterOne/lib/python3.7/site-packages/torch/cuda/_utils.py", line 31, in _get_device_index
    raise ValueError('Expected a cuda device, but got: {}'.format(device))
ValueError: Expected a cuda device, but got: cpu

```

**Comment by LorrinWWW** [comment]
Yes, you are right. These lines are fixed now, try pull the latest code to train on cpu.
